### model
model_name_or_path: /cache/data/huggingface_models/Llama-3.2-11B-Vision-Instruct
trust_remote_code: true
print_param_status: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_multi_modal_projector: false
freeze_vision_tower: false
train_mm_proj_only: false
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: data  # map your annotation to dataset_dir
image_dir:
        - data
        - data/AtomMATH/images
dataset: llava_v1_5_sample_100k, AMATH-SFT
template: mllama  # prompt template in src/llamafactory/data/template.py
cutoff_len: 4096  # model_max_length
overwrite_cache: true
preprocessing_num_workers: 64
seed: 42

### output
output_dir: /cache/exps/AtomThink/train_full/llama32-11b-vision/llava100k_amath
logging_steps: 10
logging_dir: /cache/exps/AtomThink/train_full/llama32-11b-vision/llava100k_amath/runs
report_to: tensorboard  # tensorboard or wandb or none
save_steps: 2500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2  # total batch_size=128
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
fp16: false
ddp_timeout: 180000000
image_resolution: 313600  # 560*560